FROM sapmachine/jdk11
MAINTAINER 95217902@qq.com
VOLUME /tmp
EXPOSE 8762
ADD target/eureka-server-0.0.1-SNAPSHOT.jar /eureka-server.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/eureka-server.jar","--spring.profiles.active=prod"]
