FROM sapmachine/jdk11
MAINTAINER 95217902@qq.com
VOLUME /tmp
EXPOSE 8180
ADD target/zuul-gateway-0.0.1-SNAPSHOT.jar /zuul-gateway.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/zuul-gateway.jar","--spring.profiles.active=prod"]
