FROM sapmachine/jdk11
MAINTAINER 95217902@qq.com
VOLUME /tmp
EXPOSE 8182
ADD target/file-service-0.0.1-SNAPSHOT.jar /file-service.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/file-service.jar","--spring.profiles.active=prod"]
