spring:
  application:
    name: blog-service
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.98.163.117:3306/ming_blog?useSSL=false&allowMultiQueries=true&autoReconnect=true
      username: root
      password: 123456
    cluster:
    - key: database2
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.98.163.117:3306/ming_blog?useSSL=false&allowMultiQueries=true&autoReconnect=true
      username: root
      password: 123456

  security:
    oauth2:
      client:
        clientId: blog
        clientSecret: 123456
        accessTokenUri: http://localhost:8771/oauth/token
        userAuthorizationUri: http://localhost:8771/oauth/authorize
        pre-established-redirect-uri: http://localhost:8181/hello
      resource:
        tokenInfoUri: http://localhost:8771/oauth/check_token
#        userInfoUri: http://localhost:8080/user
#        preferTokenInfo: false
      sso:
        login-path: http://localhost:8771/login
server:
  port: 8181
  servlet:
    session:
      cookie:
        name: OAUTH2SESSION
#    context-path: /blog-service

#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://eureka8761.com:8761/eureka
security:
  oauth2:
    client:
      clientId: blog
      clientSecret: 123456
      accessTokenUri: http://localhost:8771/oauth/token
      userAuthorizationUri: http://localhost:8771/oauth/authorize
      pre-established-redirect-uri: http://localhost:8181
    resource:
        tokenInfoUri: http://localhost:8771/oauth/check_token
        #        userInfoUri: http://localhost:8080/user
        #        preferTokenInfo: false
    sso:
      login-path: /

mybatis:
  config-location:  classpath:mybatis-config.xml
  type-aliases-package: com.chm.book.blog.domain
  configuration:
    map-underscore-to-camel-case: true

oauth2:
  key:
    publicKey: oauth2/rsa_public_key.pem

