spring:
  application:
    name: article-service
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.34.6.152:3306/ming_blog?useSSL=false&allowMultiQueries=true&autoReconnect=true
      username: root
      password: 123456
    cluster:
      - key: database2
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://101.34.6.152:3306/ming_blog?useSSL=false&allowMultiQueries=true&autoReconnect=true
        username: root
        password: 123456
  redis:
    host: 101.34.6.152

server:
  port: 8182

rsa:
  key:
    publicKeyPath: oauth2/rsa_public_key.pem

mybatis:
  config-location:  classpath:mybatis-config.xml
  type-aliases-package: com.chm.book.article.domain
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8762/eureka
