FROM sapmachine/jdk11 
MAINTAINER 95217902@qq.com 
VOLUME /tmp
EXPOSE 8771
ADD target/oauth2-server-0.0.1-SNAPSHOT.jar /oauth2-server.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/oauth2-server.jar","--spring.profiles.active=prod"]