spring:
  application:
    name: zuul-gateway

server:
  port: 8180

eureka:
  instance:
    prefer-ip-address: true
    instance-id: bookzuul.com
  client:
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://101.34.6.152:31071/eureka

zuul:
  sensitive-headers: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
#  ignored-services: "*"
  routes:
    auth:
      path: /oauth2/**
      service-id: oauth2-server
      strip-prefix: true
      custom-sensitive-headers: true
    myticket:
      service-id: article-service
      path: /article/**
      stripPrefix: true
    fileService:
      service-id: file-service
      path: /file/**
      stripPrefix: true

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 30000
        timeout:
          enabled: false
