
spring:
  application:
    name: file-api
  kafka:
#    bootstrap-servers: 47.98.163.117:32092
#    producer:
#      acks: -1
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
#      group-id: topic.group
      properties:
        spring:
          json:
            trusted:
              packages: com.chm.book.fileapi.domain
  redis:
    port: 32379
    host: 47.98.163.117
    timeout: 5000
    password: redis
server:
  port: 8185
