spring:
  application:
    name: oauth2-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.6.152:32306/security_authority?useSSL=false&allowMultiQueries=true&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: mysql

server:
  port: 8771

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://101.34.6.152:31071/eureka

mybatis:
  config-location:  classpath:mybatis-config.xml
  type-aliases-package: com.chm.book.oauth2.domain
  configuration:
    map-underscore-to-camel-case: true

rsa:
  key:
    publicKeyPath: oauth2/rsa_public_key.pem
    privateKeyPath: oauth2/rsa_private_key_pkcs8.pem
